#packmode expert
#modloaded etutil
#priority -100

//创造魔力池
mods.extendedcrafting.TableCrafting.addShaped(4, <botania:pool:1>, [
	[null, null, <ore:gaiaIngot>, <contenttweaker:entropy>, <contenttweaker:entropy>, <contenttweaker:entropy>, <ore:gaiaIngot>, null, null], 
	[null, <ore:gaiaIngot>, <contenttweaker:entropy>, <botania:storage:1>, <botania:storage:1>, <botania:storage:1>, <contenttweaker:entropy>, <ore:gaiaIngot>, null], 
	[<ore:gaiaIngot>, <contenttweaker:entropy>, <botania:storage:1>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <botania:storage:1>, <contenttweaker:entropy>, <ore:gaiaIngot>], 
	[<contenttweaker:entropy>, <botania:storage:1>, <botania:pool:3>, <botania:pool:3>, <contenttweaker:lunar_essence>, <botania:pool:3>, <botania:pool:3>, <botania:storage:1>, <contenttweaker:entropy>], 
	[<contenttweaker:entropy>, <botania:storage:1>, <botania:pool:3>, <contenttweaker:lunar_essence>, <astralsorcery:itemcraftingcomponent:4>, <contenttweaker:lunar_essence>, <botania:pool:3>, <botania:storage:1>, <contenttweaker:entropy>], 
	[<contenttweaker:entropy>, <botania:storage:1>, <botania:pool:3>, <botania:pool:3>, <contenttweaker:lunar_essence>, <botania:pool:3>, <botania:pool:3>, <botania:storage:1>, <contenttweaker:entropy>], 
	[<ore:gaiaIngot>, <contenttweaker:entropy>, <botania:storage:1>, <botania:pool:3>, <botania:pool:3>, <botania:pool:3>, <botania:storage:1>, <contenttweaker:entropy>, <ore:gaiaIngot>], 
	[<contenttweaker:sub_block_holder_0:8>, <ore:gaiaIngot>, <contenttweaker:entropy>, <botania:storage:1>, <botania:storage:1>, <botania:storage:1>, <contenttweaker:entropy>, <ore:gaiaIngot>, <contenttweaker:sub_block_holder_0:8>], 
	[<contenttweaker:sub_block_holder_0:8>, <contenttweaker:sub_block_holder_0:8>, <ore:gaiaIngot>, <contenttweaker:entropy>, <contenttweaker:entropy>, <contenttweaker:entropy>, <ore:gaiaIngot>, <contenttweaker:sub_block_holder_0:8>, <contenttweaker:sub_block_holder_0:8>]
]);

//创造存入升级
mods.extendedcrafting.TableCrafting.addShaped(4, <storagedrawers:upgrade_creative>, [
	[null, null, null, <contenttweaker:entropy>, <contenttweaker:entropy>, <contenttweaker:entropy>, null, null, null], 
	[null, null, <contenttweaker:entropy>, <contenttweaker:material_part:61>, <extrautils2:opinium:4>, <contenttweaker:material_part:61>, <contenttweaker:entropy>, null, null], 
	[null, <contenttweaker:entropy>, <contenttweaker:material_part:61>, <extrautils2:opinium:4>, <arcanearchives:storage_shaped_quartz>, <extrautils2:opinium:4>, <contenttweaker:material_part:61>, <contenttweaker:entropy>, null], 
	[null, <contenttweaker:entropy>, <contenttweaker:material_part:61>, <storagedrawers:upgrade_template>, <storagedrawers:upgrade_template>, <storagedrawers:upgrade_template>, <contenttweaker:material_part:61>, <contenttweaker:entropy>, null], 
	[null, <contenttweaker:entropy>, <extrautils2:opinium:4>, <storagedrawers:upgrade_template>, <storagedrawers:upgrade_template>, <storagedrawers:upgrade_template>, <extrautils2:opinium:4>, <contenttweaker:entropy>, null], 
	[null, <contenttweaker:entropy>, <contenttweaker:material_part:61>, <storagedrawers:upgrade_template>, <storagedrawers:upgrade_template>, <storagedrawers:upgrade_template>,<contenttweaker:material_part:61>, <contenttweaker:entropy>, null], 
	[null, <contenttweaker:entropy>, <contenttweaker:material_part:61>, <extrautils2:opinium:4>, <arcanearchives:storage_shaped_quartz>, <extrautils2:opinium:4>, <contenttweaker:material_part:61>, <contenttweaker:entropy>, null], 
	[null, null, <contenttweaker:entropy>, <contenttweaker:material_part:61>, <extrautils2:opinium:4>, <contenttweaker:material_part:61>, <contenttweaker:entropy>, null, null], 
	[null, null, null, <contenttweaker:entropy>, <contenttweaker:entropy>, <contenttweaker:entropy>, null, null, null]
]);

//守序者的真理
mods.extendedcrafting.TableCrafting.addShaped(4, <contenttweaker:orders_truth>, [
	[null, null, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, null, null], 
	[null, <contenttweaker:material_part:61>, <contenttweaker:aspectus_astra>, <contenttweaker:entropy>, <ore:ingotCalifornium250Base>, <contenttweaker:entropy>, <contenttweaker:aspectus_astra>, <contenttweaker:material_part:61>, null], 
	[<contenttweaker:material_part:61>, <contenttweaker:aspectus_astra>, <contenttweaker:entropy>, <ore:ingotCalifornium250Base>, <ore:ingotCalifornium250>, <ore:ingotCalifornium250Base>, <contenttweaker:entropy>, <contenttweaker:aspectus_astra>, <contenttweaker:material_part:61>], 
	[<contenttweaker:material_part:61>, <contenttweaker:entropy>, <ore:ingotCalifornium250Base>, <ore:ingotCalifornium252>, <contenttweaker:neutron>, <ore:ingotCalifornium252>, <ore:ingotCalifornium250Base>, <contenttweaker:entropy>, <contenttweaker:material_part:61>], 
	[<contenttweaker:material_part:61>, <ore:ingotCalifornium250Base>, <ore:ingotCalifornium250>, <contenttweaker:neutron>, <ore:listAllfishraw>, <contenttweaker:neutron>, <ore:ingotCalifornium250>, <ore:ingotCalifornium250Base>, <contenttweaker:material_part:61>], 
	[<contenttweaker:material_part:61>, <contenttweaker:entropy>, <ore:ingotCalifornium250Base>, <ore:ingotCalifornium252>, <contenttweaker:neutron>, <ore:ingotCalifornium252>, <ore:ingotCalifornium250Base>, <contenttweaker:entropy>, <contenttweaker:material_part:61>], 
	[<contenttweaker:material_part:61>, <contenttweaker:aspectus_astra>, <contenttweaker:entropy>, <ore:ingotCalifornium250Base>, <ore:ingotCalifornium250>, <ore:ingotCalifornium250Base>, <contenttweaker:entropy>, <contenttweaker:aspectus_astra>, <contenttweaker:material_part:61>], 
	[null, <contenttweaker:material_part:61>, <contenttweaker:aspectus_astra>, <contenttweaker:entropy>, <ore:ingotCalifornium250Base>, <contenttweaker:entropy>, <contenttweaker:aspectus_astra>, <contenttweaker:material_part:61>, null], 
	[null, null, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, <contenttweaker:material_part:61>, null, null]
]);

//终极奇点
mods.extendedcrafting.TableCrafting.addShaped(4, <extendedcrafting:singularity_ultimate>, [
	[<extendedcrafting:singularity:22>, <extendedcrafting:singularity:22>, <contenttweaker:neutron>, <contenttweaker:neutron>, <extendedcrafting:singularity_custom:84>, <contenttweaker:neutron>, <contenttweaker:neutron>, <extendedcrafting:singularity:17>, <extendedcrafting:singularity:17>], 
	[<extendedcrafting:singularity:22>, <extendedcrafting:singularity:18>, <extendedcrafting:singularity:19>, <extendedcrafting:singularity:34>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:5>, <extendedcrafting:singularity:27>, <extendedcrafting:singularity:18>, <extendedcrafting:singularity:17>], 
	[<contenttweaker:neutron>, <extendedcrafting:singularity:19>, <extendedcrafting:singularity:34>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity_custom:86>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:5>, <extendedcrafting:singularity:27>, <contenttweaker:neutron>], 
	[<contenttweaker:neutron>, <extendedcrafting:singularity:34>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:48>, <extendedcrafting:singularity:30>, <extendedcrafting:singularity:33>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:5>, <contenttweaker:neutron>], 
	[<extendedcrafting:singularity_custom:87>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:29>, <extendedcrafting:singularity_custom:90>, <extendedcrafting:singularity_custom:92>, <extendedcrafting:singularity:31>, <extendedcrafting:singularity_custom:93>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity_custom:80>], 
	[<contenttweaker:neutron>, <extendedcrafting:singularity:28>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:49>, <extendedcrafting:singularity:35>, <extendedcrafting:singularity:50>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:25>, <contenttweaker:neutron>], 
	[<contenttweaker:neutron>, <extendedcrafting:singularity:26>, <extendedcrafting:singularity:28>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity_custom:91>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:25>, <extendedcrafting:singularity:24>, <contenttweaker:neutron>], 
	[<extendedcrafting:singularity:23>, <extendedcrafting:singularity:18>, <extendedcrafting:singularity:26>, <extendedcrafting:singularity:28>, <extendedcrafting:singularity:1>, <extendedcrafting:singularity:25>, <extendedcrafting:singularity:24>, <extendedcrafting:singularity:18>, <extendedcrafting:singularity:16>], 
	[<extendedcrafting:singularity:23>, <extendedcrafting:singularity:23>, <contenttweaker:neutron>, <contenttweaker:neutron>, <extendedcrafting:singularity_custom:89>, <contenttweaker:neutron>, <contenttweaker:neutron>, <extendedcrafting:singularity:16>, <extendedcrafting:singularity:16>]
]);
//表
mods.extendedcrafting.TableCrafting.addShaped(4, <projecte:item.pe_time_watch>.withTag({}), [
	[<contenttweaker:sub_block_holder_0:8>, null, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, null, null], 
	[null, <contenttweaker:material_part:52>, <contenttweaker:neutron>, <thermalfoundation:material:326>, <thermalfoundation:material:326>, <thermalfoundation:material:326>, <contenttweaker:neutron>, <contenttweaker:material_part:52>, null], 
	[<contenttweaker:material_part:52>, <contenttweaker:neutron>, <projecte:item.pe_matter>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:326>, <contenttweaker:neutron>, <contenttweaker:material_part:52>], 
	[<contenttweaker:material_part:52>, <thermalfoundation:material:326>, <thermalfoundation:material:327>, <projecte:item.pe_matter>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:326>, <contenttweaker:material_part:52>], 
	[<contenttweaker:material_part:52>, <thermalfoundation:material:326>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <minecraft:clock>, <projecte:item.pe_matter>, <projecte:item.pe_matter>, <projecte:item.pe_matter>, <contenttweaker:material_part:52>], 
	[<contenttweaker:material_part:52>, <thermalfoundation:material:326>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:326>, <contenttweaker:material_part:52>], 
	[<contenttweaker:material_part:52>, <contenttweaker:neutron>, <thermalfoundation:material:326>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:327>, <thermalfoundation:material:326>, <contenttweaker:neutron>, <contenttweaker:material_part:52>], 
	[null, <contenttweaker:material_part:52>, <contenttweaker:neutron>, <thermalfoundation:material:326>, <thermalfoundation:material:326>, <thermalfoundation:material:326>, <contenttweaker:neutron>, <contenttweaker:material_part:52>, null], 
	[null, null, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, <contenttweaker:material_part:52>, null, null]
]);
//世界树的意志
mods.extendedcrafting.TableCrafting.addShapeless(4, <contenttweaker:will_of_world_tree>, [<minecraft:sapling>, <harvestcraft:plum_sapling>, <minecraft:sapling:2>, <harvestcraft:pecan_sapling>, <minecraft:sapling:4>, <minecraft:sapling:5>, <traverse:brown_autumnal_sapling>, <harvestcraft:almond_sapling>, <traverse:red_autumnal_sapling>, <twilightforest:twilight_sapling:6>, <twilightforest:twilight_sapling:7>, <twilightforest:twilight_sapling:3>, <harvestcraft:pawpaw_sapling>, <biomesoplenty:sapling_1>, <harvestcraft:fig_sapling>, <naturesaura:ancient_sapling>, <rustic:sapling:1>, <harvestcraft:coconut_sapling>, <twilightforest:twilight_sapling:1>, <harvestcraft:apricot_sapling>, <harvestcraft:pear_sapling>, <traverse:yellow_autumnal_sapling>, <harvestcraft:soursop_sapling>, <traverse:fir_sapling>, <harvestcraft:grapefruit_sapling>, <harvestcraft:vanillabean_sapling>, <biomesoplenty:sapling_0:7>, <biomesoplenty:sapling_0:6>, <biomesoplenty:sapling_2:2>, <biomesoplenty:sapling_1:4>, <harvestcraft:orange_sapling>, <biomesoplenty:sapling_1:2>, <biomesoplenty:sapling_1:7>, <harvestcraft:cherry_sapling>, <biomesoplenty:sapling_2:1>, <harvestcraft:lime_sapling>, <biomesoplenty:sapling_2:5>, <harvestcraft:dragonfruit_sapling>, <biomesoplenty:sapling_2:3>, <twilightforest:twilight_sapling:4>, <harvestcraft:cashew_sapling>, <traverse:orange_autumnal_sapling>, <harvestcraft:papaya_sapling>, <biomesoplenty:sapling_2:6>, <biomesoplenty:sapling_1:3>, <twilightforest:twilight_sapling:8>, <harvestcraft:lemon_sapling>, <harvestcraft:apple_sapling>, <harvestcraft:passionfruit_sapling>, <biomesoplenty:sapling_1:6>, <harvestcraft:pomegranate_sapling>, <roots:wildwood_sapling>, <harvestcraft:jackfruit_sapling>, <harvestcraft:olive_sapling>, <harvestcraft:banana_sapling>, <biomesoplenty:sapling_2:4>, <harvestcraft:pistachio_sapling>, <biomesoplenty:sapling_2>, <harvestcraft:gooseberry_sapling>, <biomesoplenty:sapling_1:1>, <twilightforest:twilight_sapling>, <harvestcraft:rambutan_sapling>, <harvestcraft:starfruit_sapling>, <harvestcraft:spiderweb_sapling>, <biomesoplenty:sapling_2:7>, <harvestcraft:date_sapling>, <minecraft:sapling:3>, <harvestcraft:avocado_sapling>, <harvestcraft:hazelnut_sapling>, <rustic:sapling>, <twilightforest:twilight_sapling:9>, <extrautils2:ironwood_sapling>, <harvestcraft:peach_sapling>, <minecraft:sapling:1>, <twilightforest:twilight_sapling:5>, <harvestcraft:peppercorn_sapling>, <biomesoplenty:sapling_0:1>, <harvestcraft:mango_sapling>, <twilightforest:twilight_sapling:2>, <biomesoplenty:sapling_1:5>, <harvestcraft:nutmeg_sapling>]);
//扭蛋收藏者纹章
mods.extendedcrafting.TableCrafting.addShaped(4, <contenttweaker:tlm_ultra>, [
	[<contenttweaker:auriminium>, null, null, null, <mekanismgenerators:reactorglass:1>, <touhou_little_maid:gashapon_coin>, <touhou_little_maid:gashapon_coin>, <contenttweaker:draconium_alloy_ingot>, <contenttweaker:draconium_alloy_ingot>], 
	[null, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:hakurei_reimu_2"}), <contenttweaker:entropy>, null, null, <mekanismgenerators:reactorglass:1>, <mekanismgenerators:reactorglass:1>, <touhou_little_maid:gashapon_coin>, <contenttweaker:draconium_alloy_ingot>], 
	[null, <contenttweaker:entropy>, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:kochiya_sanae"}), <contenttweaker:entropy>, <contenttweaker:entropy>, null, null, <mekanismgenerators:reactorglass:1>, <touhou_little_maid:gashapon_coin>], 
	[null, null, <contenttweaker:entropy>, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:izayoi_sakuya"}), <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:komeiji_satori"}), <contenttweaker:entropy>, null, <mekanismgenerators:reactorglass:1>, <touhou_little_maid:gashapon_coin>], 
	[<mekanismgenerators:reactorglass:1>, null, <contenttweaker:entropy>, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:alice_margatroid"}), <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:yukari_yakumo"}), <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:remilia_scarlet"}), <contenttweaker:entropy>, null, <mekanismgenerators:reactorglass:1>], 
	[<touhou_little_maid:gashapon_coin>, <mekanismgenerators:reactorglass:1>, null, <contenttweaker:entropy>, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:komeiji_koishi"}), <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:kirisame_marisa"}), <contenttweaker:entropy>, null, null], 
	[<touhou_little_maid:gashapon_coin>, <mekanismgenerators:reactorglass:1>, null, null, <contenttweaker:entropy>, <contenttweaker:entropy>, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:saigyouji_yuyuko"}), <contenttweaker:entropy>, null], 
	[<contenttweaker:draconium_alloy_ingot>, <touhou_little_maid:gashapon_coin>, <mekanismgenerators:reactorglass:1>, <mekanismgenerators:reactorglass:1>, null, null, <contenttweaker:entropy>, <touhou_little_maid:maid_model_coupon:5>.withTag({ModelData: "touhou_little_maid:hakurei_reimu"}), null], 
	[<contenttweaker:draconium_alloy_ingot>, <contenttweaker:draconium_alloy_ingot>, <touhou_little_maid:gashapon_coin>, <touhou_little_maid:gashapon_coin>, <mekanismgenerators:reactorglass:1>, null, null, null, <contenttweaker:auriminium>]
]);
